### ISSUE TITLE
Correct implemented algorithms

### ISSUE THREAD

**Issue by cyberfined** [AndreasPK/dom-lt#1]
All of two tests are failed.

What's wrong for first test case:
- idom
- ipdom

What's wrong for second test case:
- dom
- idom
- domTree

**Comment by AndreasPK** [comment]
Thanks! I hadn't noticed.

So the issue is that in 3ef3eefabb93316a27293230fa9c2c0d0f197998 I changed strictness semantics, which it seems changed the order in which results for nodes are returned.

The good thing is it doesn't matter for correctness. A result of `[(2,1), (3,1)]` is just as correct as one of `[(3,1), (2,1)]` for `idom`. The bad thing is that it breaks the test, and I didn't notice.

I will add some sort of ci and try to improve the tests a bit.

**Comment by AndreasPK** [comment]
After some drawing of graphs and rewriting the tests it became obvious that I actually introduced a bug .. should be reasonably easy to fix though.
